#!/bin/bash

# Catppuccin Macchiato Colors
# Format: 0xaarrggbb
BLUE=0xff8aadf4
GREY=0xff494d64
BLACK=0xff1e2030

borders active_color=$BLUE         inactive_color=$GREY         width=4.0         hidpi=on         radius=10.0
